### ISSUE TITLE
[Question] Why was the tab lab made obsolete ?

### ISSUE THREAD

**Issue by TechWatching** [ltwlf/microsoft-teams-training#7]
I was wondering why the tab lab was made obsolete, it is because there is a another way to do a tab ?

**Comment by ltwlf** [comment]
Hi, I removed the lab because the packages were outdated and it wasn’t easy to update  them. The approach is still valid and an additional option for tabs is creating a SPFx Webpart.

**Comment by TechWatching** [comment]
Okay thanks for the information. I was wondering what was the link between the tab in React.js and the bot in .NET Core but it seems it's just an `AddSpaStaticFiles` in the Startup.cs. 
Anyway thanks for the content :)
